"""SQLModel domain entities for NovaCore."""

from __future__ import annotations

from datetime import datetime, timedelta
from typing import Any, Optional
from uuid import UUID, uuid4

from sqlalchemy import Column, DateTime, JSON
from sqlmodel import Field, Relationship, SQLModel

from .enums import (
    AccountMode,
    ApprovalState,
    BrokerType,
    OrderSide,
    OrderStatus,
    OrderType,
    PositionStatus,
    SignalSide,
    SignalSource,
    StrategyStatus,
)


class TimestampMixin(SQLModel):
    """Mixin providing created/updated timestamps."""

    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        sa_column=Column(DateTime(timezone=True), nullable=False, default=datetime.utcnow),
    )
    updated_at: datetime = Field(
        default_factory=datetime.utcnow,
        sa_column=Column(
            DateTime(timezone=True),
            nullable=False,
            default=datetime.utcnow,
            onupdate=datetime.utcnow,
        ),
    )


class Tenant(TimestampMixin, SQLModel, table=True):
    """Represents an isolated tenant within Nova."""

    id: UUID = Field(default_factory=uuid4, primary_key=True, index=True)
    name: str = Field(index=True, min_length=1, max_length=100)
    slug: str = Field(index=True, min_length=1, max_length=50)
    is_active: bool = Field(default=True, index=True)

    users: list["User"] = Relationship(back_populates="tenant")
    api_keys: list["ApiKey"] = Relationship(back_populates="tenant")
    strategies: list["Strategy"] = Relationship(back_populates="tenant")
    trading_accounts: list["TradingAccount"] = Relationship(back_populates="tenant")


class User(TimestampMixin, SQLModel, table=True):
    """Tenant-scoped user model."""

    id: UUID = Field(default_factory=uuid4, primary_key=True, index=True)
    tenant_id: UUID = Field(foreign_key="tenant.id", index=True)
    email: str = Field(index=True, min_length=3, max_length=320)
    hashed_password: str = Field(min_length=32, max_length=256)
    role: str = Field(default="analyst", min_length=2, max_length=50)
    is_active: bool = Field(default=True)

    tenant: Tenant = Relationship(back_populates="users")


class ApiKey(TimestampMixin, SQLModel, table=True):
    """API key allowing programmatic access."""

    id: UUID = Field(default_factory=uuid4, primary_key=True, index=True)
    tenant_id: UUID = Field(foreign_key="tenant.id", index=True)
    name: str = Field(min_length=1, max_length=100)
    hashed_key: str = Field(min_length=32, max_length=256, index=True)
    description: Optional[str] = Field(default=None, max_length=255)
    is_active: bool = Field(default=True, index=True)

    tenant: Tenant = Relationship(back_populates="api_keys")


class Strategy(TimestampMixin, SQLModel, table=True):
    """Trading strategy configuration."""

    id: UUID = Field(default_factory=uuid4, primary_key=True, index=True)
    tenant_id: UUID = Field(foreign_key="tenant.id", index=True)
    name: str = Field(min_length=1, max_length=120, index=True)
    description: Optional[str] = Field(default=None, max_length=1024)
    params: dict[str, Any] = Field(
        default_factory=dict,
        sa_column=Column(JSON, nullable=False, default=dict),
    )
    version: str = Field(default="1.0.0", min_length=1, max_length=50)
    status: StrategyStatus = Field(default=StrategyStatus.DRAFT)
    created_by: Optional[UUID] = Field(default=None, foreign_key="user.id")

    tenant: Tenant = Relationship(back_populates="strategies")
    signals: list["Signal"] = Relationship(back_populates="strategy")


class TradingAccount(TimestampMixin, SQLModel, table=True):
    """Broker account used for strategy execution."""

    id: UUID = Field(default_factory=uuid4, primary_key=True, index=True)
    tenant_id: UUID = Field(foreign_key="tenant.id", index=True)
    name: str = Field(min_length=1, max_length=120)
    broker: BrokerType = Field(default=BrokerType.ALPACA)
    mode: AccountMode = Field(default=AccountMode.PAPER)
    credentials_ref: str = Field(min_length=1, max_length=255)
    balance_cache: float = Field(default=0.0)

    tenant: Tenant = Relationship(back_populates="trading_accounts")
    orders: list["Order"] = Relationship(back_populates="account")
    positions: list["Position"] = Relationship(back_populates="account")


class Signal(TimestampMixin, SQLModel, table=True):
    """Signals generated by strategies or external sources."""

    id: UUID = Field(default_factory=uuid4, primary_key=True, index=True)
    tenant_id: UUID = Field(foreign_key="tenant.id", index=True)
    strategy_id: Optional[UUID] = Field(default=None, foreign_key="strategy.id", index=True)
    symbol: str = Field(min_length=1, max_length=32, index=True)
    side: SignalSide = Field(default=SignalSide.LONG)
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)
    ttl_seconds: int = Field(default=300, ge=0)
    source: SignalSource = Field(default=SignalSource.STRATEGY)
    expires_at: Optional[datetime] = Field(default=None, index=True)

    strategy: Optional[Strategy] = Relationship(back_populates="signals")

    def compute_expiry(self) -> datetime:
        """Compute and set the expiration timestamp based on TTL."""

        expiry = datetime.utcnow() + timedelta(seconds=self.ttl_seconds)
        self.expires_at = expiry
        return expiry


class Order(TimestampMixin, SQLModel, table=True):
    """Order generated from a signal or manual action."""

    id: UUID = Field(default_factory=uuid4, primary_key=True, index=True)
    tenant_id: UUID = Field(foreign_key="tenant.id", index=True)
    account_id: UUID = Field(foreign_key="tradingaccount.id", index=True)
    signal_id: Optional[UUID] = Field(default=None, foreign_key="signal.id", index=True)
    symbol: str = Field(min_length=1, max_length=32, index=True)
    side: OrderSide = Field(default=OrderSide.BUY)
    type: OrderType = Field(default=OrderType.MARKET)
    status: OrderStatus = Field(default=OrderStatus.NEW)
    quantity: float = Field(gt=0)
    limit_price: Optional[float] = Field(default=None, ge=0)
    stop_price: Optional[float] = Field(default=None, ge=0)
    provider_order_id: Optional[str] = Field(default=None, max_length=120, index=True)
    tx_hash: Optional[str] = Field(default=None, max_length=120, index=True)
    submitted_at: Optional[datetime] = Field(default=None)
    filled_at: Optional[datetime] = Field(default=None)
    canceled_at: Optional[datetime] = Field(default=None)
    metadata: dict[str, Any] | None = Field(
        default=None,
        sa_column=Column(JSON, nullable=True),
    )

    account: TradingAccount = Relationship(back_populates="orders")


class Position(TimestampMixin, SQLModel, table=True):
    """Represents an open or closed trading position."""

    id: UUID = Field(default_factory=uuid4, primary_key=True, index=True)
    tenant_id: UUID = Field(foreign_key="tenant.id", index=True)
    account_id: UUID = Field(foreign_key="tradingaccount.id", index=True)
    symbol: str = Field(min_length=1, max_length=32, index=True)
    status: PositionStatus = Field(default=PositionStatus.OPEN)
    quantity: float = Field(gt=0)
    average_price: float = Field(ge=0)
    unrealized_pl: float = Field(default=0.0)
    opened_at: datetime = Field(default_factory=datetime.utcnow)
    closed_at: Optional[datetime] = Field(default=None)

    account: TradingAccount = Relationship(back_populates="positions")


class Manifest(TimestampMixin, SQLModel, table=True):
    """Describes capabilities and configuration for an autonomous agent."""

    id: UUID = Field(default_factory=uuid4, primary_key=True, index=True)
    tenant_id: UUID = Field(foreign_key="tenant.id", index=True)
    version: str = Field(default="1.0.0", min_length=1, max_length=50)
    content: dict[str, Any] = Field(
        default_factory=dict,
        sa_column=Column(JSON, nullable=False, default=dict),
    )


class Agent(TimestampMixin, SQLModel, table=True):
    """Agent participating in Nova workflows."""

    id: UUID = Field(default_factory=uuid4, primary_key=True, index=True)
    tenant_id: UUID = Field(foreign_key="tenant.id", index=True)
    name: str = Field(min_length=1, max_length=120)
    role: str = Field(default="generalist", min_length=1, max_length=120)
    manifest_id: Optional[UUID] = Field(default=None, foreign_key="manifest.id")
    is_active: bool = Field(default=True)


class Approval(TimestampMixin, SQLModel, table=True):
    """Approval record for signals or orders before execution."""

    id: UUID = Field(default_factory=uuid4, primary_key=True, index=True)
    tenant_id: UUID = Field(foreign_key="tenant.id", index=True)
    signal_id: Optional[UUID] = Field(default=None, foreign_key="signal.id", index=True)
    order_id: Optional[UUID] = Field(default=None, foreign_key="order.id", index=True)
    state: ApprovalState = Field(default=ApprovalState.PENDING)
    approver: Optional[str] = Field(default=None, max_length=120)
    reason: Optional[str] = Field(default=None, max_length=500)
    decided_at: Optional[datetime] = Field(default=None)
